lib/auth1_web/router.ex
defmodule Auth1Web.Router do
  use Auth1Web, :router

  import Auth1Web.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {Auth1Web.LayoutView, :root}

    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Auth1Web do
    pipe_through [:browser, :require_authenticated_user]

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Auth1Web do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: Auth1Web.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", Auth1Web do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users1/register", UserRegistrationController, :new
    post "/users1/register", UserRegistrationController, :create
    get "/users1/log_in", UserSessionController, :new
    post "/users1/log_in", UserSessionController, :create
    get "/users1/reset_password", UserResetPasswordController, :new
    post "/users1/reset_password", UserResetPasswordController, :create
    get "/users1/reset_password/:token", UserResetPasswordController, :edit
    put "/users1/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", Auth1Web do
    pipe_through [:browser, :require_authenticated_user]

    get "/users1/settings", UserSettingsController, :edit
    put "/users1/settings", UserSettingsController, :update
    get "/users1/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", Auth1Web do
    pipe_through [:browser]

    delete "/users1/log_out", UserSessionController, :delete
    get "/users1/confirm", UserConfirmationController, :new
    post "/users1/confirm", UserConfirmationController, :create
    get "/users1/confirm/:token", UserConfirmationController, :edit
    post "/users1/confirm/:token", UserConfirmationController, :update
  end
end

lib/auth1_web/controllers/user_registration_controller.ex
defmodule Auth1Web.UserRegistrationController do
  use Auth1Web, :controller

  alias Auth1.Accounts
  alias Auth1.Accounts.User
  alias Auth1Web.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/auth1_web/views/user_registration_view.ex
defmodule Auth1Web.UserRegistrationView do
  use Auth1Web, :view
end

lib/auth1_web/templates/user_registration/new.html.heex
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Browser</title>
</head>

<body>
 <div class="splitl">
  <div class="diagonal-boxu"></div>   
   <div class="diagonal-boxd"></div>
   <div class="con">
     <div class="signup">Sign Up</div>
   </div>
   <div class="con2">Login</div>
</div>
  
  <div class="splitr">
  	<div class="heading">Create new account</div> <br/><br/><br/><br/>
    <div class= "h2">Already A Member? Log In</div> <br/>
    <div class="container">
    	<.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
        <%= if @changeset.action do %>
          <div class="alert alert-danger">
              <p>Oops, something went wrong! Please check the errors below.</p>
          </div>
        <% end %>
        <%= label f, :name %>
        <%= text_input f, :name, required: true , placeholder: "First Name"%> <br>
        <%= label f, :email %>
        <%= email_input f, :email, required: true , placeholder: "Example@gmail.com"%> 
        <%= error_tag f, :email %> <br>
        <%= label f, :password %>
        <%= password_input f, :password, required: true %>
        <%= error_tag f, :password %><br>
        <%= label f, :confirmpassword %>
        <%= password_input f, :confirmpassword, required: true %>
        <%= error_tag f, :confirmpassword %><br>
        <div>
          <%= submit  "Create Account" %>
        </div>
    	</.form>
    </div>
  </div>

<p>
  <%= link "Log in", to: Routes.user_session_path(@conn, :new) %> |
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
</p>

</body>